### Task 1
Data Cleaning Challenge on Sales Data

In [1]:
import pandas as pd

data_2017 = pd.read_csv("dataset/sales_2017.csv")
data_2018 = pd.read_csv("dataset/sales_2018.csv")
data_2019 = pd.read_csv("dataset/sales_2019.csv")

all_sales = pd.concat(objs = [data_2017, data_2018, data_2019])
all_sales

all_sales.shape

(111206, 9)

In [2]:
del all_sales["Voucher Amount"]
del all_sales["Gross"]
del all_sales["Disc"]

In [3]:
all_sales.dtypes

Date       str
Voucher    str
Party      str
Product    str
Qty        str
Rate       str
dtype: object

In [4]:
all_sales = all_sales.apply(lambda col: col.str.strip())
all_sales = all_sales.replace(r'^\s*$', pd.NA, regex=True, inplace=True)

all_sales.dropna(inplace=True)
all_sales.shape

(95561, 6)

In [5]:
# Change in Data Type

all_sales['Date'] = pd.to_datetime(all_sales['Date'], format = '%d/%m/%Y')

all_sales['Voucher'] = all_sales['Voucher'].str.replace("Sal:","").astype(float).astype(int)

all_sales['Rate'] = all_sales['Rate'].str.replace(',',"").astype(float)

all_sales['Qty'] = all_sales['Qty'].str.replace(',',"").astype(float).astype(int)

all_sales[['Party', 'Product']] = all_sales[['Party', 'Product']].astype(object)

In [6]:
all_sales.dtypes

Date       datetime64[us]
Voucher             int64
Party              object
Product            object
Qty                 int64
Rate              float64
dtype: object

In [7]:
all_sales.duplicated().sum()

np.int64(340)

In [8]:
all_sales.drop_duplicates(inplace=True)

In [9]:
all_sales.shape

(95221, 6)

In [10]:
print(all_sales.isnull().sum())

Date       0
Voucher    0
Party      0
Product    0
Qty        0
Rate       0
dtype: int64

In [11]:
print(all_sales.duplicated().sum())

0

In [ ]:
all_sales.head(10)

In [ ]:
all_sales = all_sales.to_csv("updateSales.csv", index=False)

### Task 2
Merge Function 1 Example

In [7]:
# merge function

import pandas as pd

emp1 = pd.read_csv("dataset/employee_data1.csv")
emp2 = pd.read_csv("dataset/employee_data2.csv")

combine = emp1.merge(emp2, how="outer")
combine

      Name   Age Department   Salary  Gender EmployeeID
0     Anbu  32.0        Ops  62000.0    Male     EID009
1  Bhavani  40.0         IT  64000.0     NaN        NaN
2   Geetha  31.0    IT Tech  57000.0     NaN        NaN
3  Gilbert  29.0        Ops  60000.0    Male     EID001
4    Kevin  28.0    Support  61000.0    Male     EID003
5  Mathiew  27.0    Support  58000.0     NaN        NaN
6    Nasir  31.0    IT Tech  50000.0  Female     EID002
7    Navin   NaN        NaN      NaN    Male     EID006
8   Rajesh  29.0        Ops  60000.0    Male     EID004

In [15]:
combine = emp1.merge(emp2, how="inner")
combine

      Name  Age Department  Salary  Gender EmployeeID
0   Rajesh   29        Ops   60000    Male     EID004
1    Nasir   31    IT Tech   50000  Female     EID002
2  Gilbert   29        Ops   60000    Male     EID001
3    Kevin   28    Support   61000    Male     EID003
4     Anbu   32        Ops   62000    Male     EID009

In [ ]:
employee_datum = emp1.merge(emp2, how="right")
employee_datum

      Name   Age Department   Salary  Gender EmployeeID
0   Rajesh  29.0        Ops  60000.0    Male     EID004
1    Nasir  31.0    IT Tech  50000.0  Female     EID002
2     Anbu  32.0        Ops  62000.0    Male     EID009
3  Gilbert  29.0        Ops  60000.0    Male     EID001
4    Kevin  28.0    Support  61000.0    Male     EID003
5    Navin   NaN        NaN      NaN    Male     EID006

In [25]:
employee_datum = emp1.merge(emp2).sort_values("EmployeeID")
employee_datum = employee_datum.reindex(columns=['EmployeeID', 'Name', 'Age', 'Gender', 'Department', 'Salary'])
employee_datum

  EmployeeID     Name  Age  Gender Department  Salary
3     EID001  Gilbert   29    Male        Ops   60000
1     EID002    Nasir   31  Female    IT Tech   50000
4     EID003    Kevin   28    Male    Support   61000
0     EID004   Rajesh   29    Male        Ops   60000
6     EID005   Geetha   31  Female    IT Tech   57000
8     EID006    Navin   28    Male    IT Tech   55000
2     EID007  Mathiew   27    Male    Support   58000
5     EID008  Bhavani   40  Female         IT   64000
7     EID009     Anbu   32    Male        Ops   62000

### Task 3
List Comprehension 2 examples

In [10]:
# Example 1

coin = [(i,j) for i in ['H','T'] for j in ['H','T']]
print(coin)

[('H', 'H'), ('H', 'T'), ('T', 'H'), ('T', 'T')]

In [11]:
# Example2

word = input("Enter the name: ")

condition_1 = [i for i in word if i not in 'aeiouAEIOU']
print(f"Word '{word}' consonants are - *{''.join(condition_1)}*")

condition_2 = [i if i not in 'aeiouAEIOU' else '_' for i in word]
print(f"Word : {''.join(condition_2)}")

Word 'fluctuation' consonants are - *flcttn*
Word : fl_ct__t__n

### Task 4
Lambda Function 2 examples with Map, Filter, Reduce

In [22]:
# Example 1 - map

list_1 = [1,2,3,4,5]
list_2 = [6,7,8,1,2]

result = map(lambda x, y: x + y, list_1, list_2)
print(list(result))

[7, 9, 11, 5, 7]

In [ ]:
# Example 2 - map

demo = [50,45,60,70,80,95]

operation1 = map(lambda answer: answer/5, demo)
print(list(operation1))                         # using map and lambda


def div(a):
    return a/10
operation2 = map(div,demo)

print(list(operation2))                         # using only map

[10.0, 9.0, 12.0, 14.0, 16.0, 19.0]
[5.0, 4.5, 6.0, 7.0, 8.0, 9.5]

In [4]:
# Example 1 - filter

number_filter = "You know! The *Report*, published in 2025, contains information about ancient sculptures dating back to around 2000 BC."
l = list(filter(lambda a: a == '*' or a == ',' or a == '!' or a == '.' or a >= '0' and a <= '9', number_filter))
print(f"Length : {len(l)}, {l}")

Length : 14, ['!', '*', '*', ',', '2', '0', '2', '5', ',', '2', '0', '0', '0', '.']

In [21]:
# Example 2 - filter

Age = [34,65,78,24,17,42,67,14,10,45,9,2,34]
list(filter(lambda a:a >= 18, Age))

[34, 65, 78, 24, 42, 67, 45, 34]

In [17]:
# Example 1 - reduce

from functools import reduce

data = ['p','y','t','h','o','n']
mul = lambda m, d : m + d
reduce(mul,data)

'python'

In [29]:
# Example 2 - reduce

from functools import reduce

fibonacci = [0,1,1,2,3,5,8,13,21]

mul = lambda m, fact : m + fact
reduce(mul,fibonacci)

54