### 1.	Write a program to take a name and age from the user and print a greeting message.

In [1]:
name = input("Please enter your name: ")
age = int(input("Please enter your age: "))
print(f"Hello, {name.capitalize()}! You are {age} years old. Welcome to the program!")

Hello, Sita! You are 25 years old. Welcome to the program!

### 2.	Create a list of numbers and print only even numbers using a for loop

In [2]:
numbers = [12,6,34,7,5,8,9,10,11,15,20,25,30]
print("Even numbers")
for even in numbers:
    if even % 2 == 0:
        print(even,end=" ")

Even numbers
12 6 34 8 10 20 30

### 3.	Write a program that handles division by zero using try-except

In [3]:
val = 10
try:
    div_by_zero = val/0
    print("Division result: {:.1f}".format(div_by_zero))
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")

Error: Division by zero is not allowed.

### 4. Given a string, count how many vowels it has.

In [ ]:
string = input("Please enter a string: ")
vowels = "aeiouAEIOU"
count = 0

for i in string:
    if i in vowels:
        count += 1
print(f"Word '{string}' contains {count} vowels")

### 5.	Reverse a list without using built-in functions.

In [ ]:
reverse_list = [10,20,30,40,50,60,70,80,90,100]
l = len(reverse_list) - 1
while l >= 0:
    print(reverse_list[l], end=" ")
    l -= 1

100 90 80 70 60 50 40 30 20 10

### 6.	Create a dictionary with at least 5 key-value pairs and print them.

In [ ]:
import pandas as pd

stock = {"motor": [10, "long_last", "heavy"], 
         "head_light": [6, "short_last", "light_weight"], 
         "tail_light": [8, "medium_last", "light_weight"], 
         "battery": [5, "high_capacity", "heavy"], 
         "tire": [12, "durable", "heavy"]}
stock_items = pd.DataFrame(stock)
print(stock_items)

       motor    head_light    tail_light        battery     tire
0         10             6             8              5       12
1  long_last    short_last   medium_last  high_capacity  durable
2      heavy  light_weight  light_weight          heavy    heavy

### 7.	Write a Pandas code to read a CSV and print the top 5 rows.

In [ ]:
import pandas as pd

sport_data = pd.read_csv("sports.csv")
sport_data.head()

     Name Location     Sport
0   Aadhi  Chennai  Football
1  Renuka  Madurai  Football
2   Meena  Madurai    Hockey
3  Suresh  Chennai   Cricket
4    Ravi    Kovai   Cricket

### 8.	Create a DataFrame from a Python dictionary.

In [ ]:
import pandas as pd

fruits_info = {
    "Fruits": ["Apple", "Banana", "Orange", "Grapes", "Mango"],
    "Availability": ["In Stock", "Out of Stock", "In Stock", "In Stock", "Out of Stock"],
    "Price": [120, 100, 150, 90, 180]}

fruits = pd.DataFrame(fruits_info)
print(fruits)

   Fruits  Availability  Price
0   Apple      In Stock    120
1  Banana  Out of Stock    100
2  Orange      In Stock    150
3  Grapes      In Stock     90
4   Mango  Out of Stock    180

### 9.	Replace all missing values in a DataFrame with the column’s mean.

In [ ]:
import pandas as pd

sport_data = pd.read_csv("sports.csv")
sport_data[sport_data["Fees"].isnull()]

      Name Location    Sport  Fees  Age
3   Suresh  Chennai  Cricket   NaN   35
6     Suba  Chennai   Hockey   NaN   37
10   Kumar  Chennai   Hockey   NaN   25

In [ ]:
sport_data = pd.read_csv("sports.csv")

new_cricket_fee = sport_data[sport_data["Sport"]=="Cricket"]["Fees"].mean()
sport_data.loc[(sport_data["Sport"]=="Cricket") & (sport_data["Fees"].isnull()), "Fees"] = new_cricket_fee

new_hockey_fee = sport_data[sport_data["Sport"]=="Hockey"]["Fees"].mean()
sport_data.loc[(sport_data["Sport"]=="Hockey") & (sport_data["Fees"].isnull()), "Fees"] = new_hockey_fee

print("Cricket fee mean: ",new_cricket_fee)
print("Hockey fee mean: ",new_hockey_fee)

sport_data.to_csv("sports.csv", index=False)

sport_data

Cricket fee mean:  1250.0
Hockey fee mean:  1300.0

      Name Location       Sport    Fees  Age
0    Aadhi  Chennai    Football  1000.0   27
1   Renuka  Madurai    Football  1200.0   20
2    Meena  Madurai      Hockey  1100.0   30
3   Suresh  Chennai     Cricket  1250.0   35
4     Ravi    Kovai     Cricket  1200.0   32
5     Siva  Chennai      Hockey  1500.0   23
6     Suba  Chennai      Hockey  1300.0   37
7    Leela    Salem  Throw ball  1500.0   42
8     Babu   Trichy  Throw ball  1400.0   22
9     Mani    Salem     Cricket  1300.0   28
10   Kumar  Chennai      Hockey  1300.0   25

### 10.	Filter rows in a DataFrame where the "Age" column is greater than 30

In [ ]:
import pandas as pd

sport_data = pd.read_csv("sports.csv")
sport_data[sport_data["Age"]>30]

     Name Location       Sport    Fees  Age
3  Suresh  Chennai     Cricket  1250.0   35
4    Ravi    Kovai     Cricket  1200.0   32
6    Suba  Chennai      Hockey  1300.0   37
7   Leela    Salem  Throw ball  1500.0   42