In [2]:
import pandas as pd

emp1 = pd.read_csv("dataset/employee_data1.csv")
emp2 = pd.read_csv("dataset/employee_data2.csv")
emp1.head()

      Name  Age Department  Salary
0   Rajesh   29        Ops   60000
1    Nasir   31    IT Tech   50000
2  Mathiew   27    Support   58000
3  Gilbert   29        Ops   60000
4    Kevin   28    Support   61000

In [3]:
emp1.groupby(by="Department")["Salary"].sum().sort_values()

Department
IT          64000
Support    119000
IT Tech    162000
Ops        182000
Name: Salary, dtype: int64

In [23]:
pd.pivot_table(data=emp1, index="Department", values="Salary", aggfunc=sum).sort_values(by="Salary", ascending=False)

            Salary
Department
Ops         182000
IT Tech     162000
Support     119000
IT           64000

In [112]:
emp1.groupby(by="Department")["Salary"].agg(func=['min','max','sum','mean']).round(2)

              min    max     sum      mean
Department
IT          64000  64000   64000  64000.00
IT Tech     50000  57000  162000  54000.00
Ops         60000  62000  182000  60666.67
Support     58000  61000  119000  59500.00

In [3]:
merged_data = pd.merge(emp1,emp2,how="outer")
merged_data.head()

      Name  Age Department  Salary  Gender EmployeeID
0     Anbu   32        Ops   62000    Male     EID009
1  Bhavani   40         IT   64000  Female     EID008
2   Geetha   31    IT Tech   57000  Female     EID005
3  Gilbert   29        Ops   60000    Male     EID001
4    Kevin   28    Support   61000    Male     EID003

In [7]:
pd.crosstab(index = merged_data['Department'], columns = merged_data['Gender'], margins=True)

Gender      Female  Male  All
Department
IT               1     0    1
IT Tech          2     1    3
Ops              0     3    3
Support          0     2    2
All              3     6    9

In [43]:
merged_data.head(3)

      Name  Age Department  Salary  Gender EmployeeID
0     Anbu   32        Ops   62000    Male     EID009
1  Bhavani   40         IT   64000  Female     EID008
2   Geetha   31    IT Tech   57000  Female     EID005

In [44]:
merged_data["Health Checkup"] = merged_data["Age"].apply(lambda a: "Mandatory" if a>30 else "Not mandatory")

In [45]:
def games(dept):
    if dept == "IT" or dept == "IT Tech":
        return "Handball"
    else:
        return "Badminton"

merged_data["Game"] = merged_data["Department"].apply(games)
merged_data.head(2)

,Name,Age,Department,Salary,Gender,EmployeeID,Health Checkup,Game
0,Anbu,32,Ops,62000,Male,EID009,Mandatory,Badminton
1,Bhavani,40,IT,64000,Female,EID008,Mandatory,Handball

In [46]:
merged_data.rename(columns={"Game":"Event Games"}, inplace=True)
merged_data.head(2)

,Name,Age,Department,Salary,Gender,EmployeeID,Health Checkup,Event Games
0,Anbu,32,Ops,62000,Male,EID009,Mandatory,Badminton
1,Bhavani,40,IT,64000,Female,EID008,Mandatory,Handball

In [47]:
merged_data.columns = merged_data.columns.str.replace("Event Games","Events")
merged_data.head(2)

,Name,Age,Department,Salary,Gender,EmployeeID,Health Checkup,Events
0,Anbu,32,Ops,62000,Male,EID009,Mandatory,Badminton
1,Bhavani,40,IT,64000,Female,EID008,Mandatory,Handball