In [1]:
import pandas as pd

sport = pd.read_csv("sports.csv")
sport

      Name Location       Sport       Fees  Age
0    Aadhi  Chennai    Football        NaN   27
1   Renuka  Madurai    Football  Rs.1200.0   20
2    Meena  Madurai      Hockey  Rs.1100.0   30
3   Suresh  Chennai     Cricket  Rs.1250.0   35
4     Ravi    Kovai     Cricket        NaN   32
5     Siva  Chennai      Hockey        NaN   23
6     Suba  Chennai      Hockey        NaN   37
7    Leela    Salem  Throw ball  Rs.1500.0   42
8     Babu   Trichy  Throw ball  Rs.1400.0   22
9     Mani    Salem         NaN  Rs.1300.0   28
10   Kumar  Chennai         NaN  Rs.1300.0   25
11    Siva  Chennai      Hockey        NaN   23
12    Suba  Chennai      Hockey        NaN   37

In [3]:
sport[sport["Fees"].isnull()]

     Name Location     Sport Fees  Age
0   Aadhi  Chennai  Football  NaN   27
4    Ravi    Kovai   Cricket  NaN   32
5    Siva  Chennai    Hockey  NaN   23
6    Suba  Chennai    Hockey  NaN   37
11   Siva  Chennai    Hockey  NaN   23
12   Suba  Chennai    Hockey  NaN   37

In [23]:
sport["Fees"]=sport["Fees"].fillna(1223.0)
sport

      Name Location       Sport    Fees  Age
0    Aadhi  Chennai    Football  1223.0   27
1   Renuka  Madurai    Football  1200.0   20
2    Meena  Madurai      Hockey  1100.0   30
3   Suresh  Chennai     Cricket  1250.0   35
4     Ravi    Kovai     Cricket  1223.0   32
5     Siva  Chennai      Hockey  1223.0   23
6     Suba  Chennai      Hockey  1223.0   37
7    Leela    Salem  Throw ball  1500.0   42
8     Babu   Trichy  Throw ball  1400.0   22
9     Mani    Salem     Cricket  1300.0   28
10   Kumar  Chennai      Hockey  1300.0   25

In [25]:
sport["Fees"]=sport["Fees"].astype(int)
sport

      Name Location       Sport  Fees  Age
0    Aadhi  Chennai    Football  1223   27
1   Renuka  Madurai    Football  1200   20
2    Meena  Madurai      Hockey  1100   30
3   Suresh  Chennai     Cricket  1250   35
4     Ravi    Kovai     Cricket  1223   32
5     Siva  Chennai      Hockey  1223   23
6     Suba  Chennai      Hockey  1223   37
7    Leela    Salem  Throw ball  1500   42
8     Babu   Trichy  Throw ball  1400   22
9     Mani    Salem     Cricket  1300   28
10   Kumar  Chennai      Hockey  1300   25

In [28]:
sport.describe()

              Fees        Age
count    11.000000  11.000000
mean   1267.454545  29.181818
std     107.034914   6.823755
min    1100.000000  20.000000
25%    1223.000000  24.000000
50%    1223.000000  28.000000
75%    1300.000000  33.500000
max    1500.000000  42.000000

In [27]:
sport.describe(include="all")

         Name Location   Sport         Fees        Age
count      11       11      11    11.000000  11.000000
unique     11        5       4          NaN        NaN
top     Aadhi  Chennai  Hockey          NaN        NaN
freq        1        5       4          NaN        NaN
mean      NaN      NaN     NaN  1267.454545  29.181818
std       NaN      NaN     NaN   107.034914   6.823755
min       NaN      NaN     NaN  1100.000000  20.000000
25%       NaN      NaN     NaN  1223.000000  24.000000
50%       NaN      NaN     NaN  1223.000000  28.000000
75%       NaN      NaN     NaN  1300.000000  33.500000
max       NaN      NaN     NaN  1500.000000  42.000000

In [35]:
sport.head()

     Name Location     Sport  Fees  Age
0   Aadhi  Chennai  Football  1223   27
1  Renuka  Madurai  Football  1200   20
2   Meena  Madurai    Hockey  1100   30
3  Suresh  Chennai   Cricket  1250   35
4    Ravi    Kovai   Cricket  1223   32

In [60]:
sport.groupby(by="Name")["Sport"].sum().sort_values()

Name
Mani         Cricket
Ravi         Cricket
Suresh       Cricket
Aadhi       Football
Renuka      Football
Kumar         Hockey
Meena         Hockey
Siva          Hockey
Suba          Hockey
Babu      Throw ball
Leela     Throw ball
Name: Sport, dtype: str

In [ ]:
#sport["Location"].unique()

sport.nunique()

Name        11
Location     5
Sport        4
Fees         7
Age         11
dtype: int64

In [48]:
sport[["Location","Name"]].head()

  Location    Name
0  Chennai   Aadhi
1  Madurai  Renuka
2  Madurai   Meena
3  Chennai  Suresh
4    Kovai    Ravi

In [ ]:
sport.sort_values(by=["Age"])

      Name Location       Sport  Fees  Age
1   Renuka  Madurai    Football  1200   20
8     Babu   Trichy  Throw ball  1400   22
5     Siva  Chennai      Hockey  1223   23
10   Kumar  Chennai      Hockey  1300   25
0    Aadhi  Chennai    Football  1223   27
9     Mani    Salem     Cricket  1300   28
2    Meena  Madurai      Hockey  1100   30
4     Ravi    Kovai     Cricket  1223   32
3   Suresh  Chennai     Cricket  1250   35
6     Suba  Chennai      Hockey  1223   37
7    Leela    Salem  Throw ball  1500   42

In [69]:
sport["Location"]=="Chennai"

sport[(sport["Location"]=="Chennai") & (sport["Sport"]=="Hockey")]

     Name Location   Sport  Fees  Age
5    Siva  Chennai  Hockey  1223   23
6    Suba  Chennai  Hockey  1223   37
10  Kumar  Chennai  Hockey  1300   25

In [72]:
sport.shape

(11, 5)

## Duplicates

In [81]:
import pandas as pd
sport = pd.read_csv("sports.csv")
sport

      Name Location       Sport       Fees  Age
0    Aadhi  Chennai    Football        NaN   27
1   Renuka  Madurai    Football  Rs.1200.0   20
2    Meena  Madurai      Hockey  Rs.1100.0   30
3   Suresh  Chennai     Cricket  Rs.1250.0   35
4     Ravi    Kovai     Cricket        NaN   32
5     Siva  Chennai      Hockey        NaN   23
6     Suba  Chennai      Hockey        NaN   37
7    Leela    Salem  Throw ball  Rs.1500.0   42
8     Babu   Trichy  Throw ball  Rs.1400.0   22
9     Mani    Salem         NaN  Rs.1300.0   28
10   Kumar  Chennai         NaN  Rs.1300.0   25
11    Siva  Chennai      Hockey        NaN   23
12    Suba  Chennai      Hockey        NaN   37

In [6]:
sport[sport.duplicated(keep=False)]

    Name Location   Sport Fees  Age
5   Siva  Chennai  Hockey  NaN   23
6   Suba  Chennai  Hockey  NaN   37
11  Siva  Chennai  Hockey  NaN   23
12  Suba  Chennai  Hockey  NaN   37

In [ ]:
sport[sport.duplicated(keep=False)]

sport.drop_duplicates(inplace=True)
sport

      Name Location       Sport       Fees  Age
0    Aadhi  Chennai    Football        NaN   27
1   Renuka  Madurai    Football  Rs.1200.0   20
2    Meena  Madurai      Hockey  Rs.1100.0   30
3   Suresh  Chennai     Cricket  Rs.1250.0   35
4     Ravi    Kovai     Cricket        NaN   32
5     Siva  Chennai      Hockey        NaN   23
6     Suba  Chennai      Hockey        NaN   37
7    Leela    Salem  Throw ball  Rs.1500.0   42
8     Babu   Trichy  Throw ball  Rs.1400.0   22
9     Mani    Salem         NaN  Rs.1300.0   28
10   Kumar  Chennai         NaN  Rs.1300.0   25

In [66]:
# sport.info()
sport.dtypes
#sport["Fees"].dtypes
#type(sport)                # pandas.DataFrame
#type(sport["Fees"])        # pandas.Series
#type(sport["Name"].values) # pandas.arrays.StringArray

Name          str
Location      str
Sport         str
Fees          str
Age         int64
dtype: object

In [83]:
sport.dropna(subset=["Fees"], inplace=True)
sport

      Name Location       Sport       Fees  Age
1   Renuka  Madurai    Football  Rs.1200.0   20
2    Meena  Madurai      Hockey  Rs.1100.0   30
3   Suresh  Chennai     Cricket  Rs.1250.0   35
7    Leela    Salem  Throw ball  Rs.1500.0   42
8     Babu   Trichy  Throw ball  Rs.1400.0   22
9     Mani    Salem         NaN  Rs.1300.0   28
10   Kumar  Chennai         NaN  Rs.1300.0   25

In [84]:
try:
    sport["Fees"] = sport["Fees"].str.replace("Rs.", "").astype(float).astype(int)
except:
    pass
sport

      Name Location       Sport  Fees  Age
1   Renuka  Madurai    Football  1200   20
2    Meena  Madurai      Hockey  1100   30
3   Suresh  Chennai     Cricket  1250   35
7    Leela    Salem  Throw ball  1500   42
8     Babu   Trichy  Throw ball  1400   22
9     Mani    Salem         NaN  1300   28
10   Kumar  Chennai         NaN  1300   25

In [85]:
sport["Sport"] = sport["Sport"].fillna("Tennis")
sport

      Name Location       Sport  Fees  Age
1   Renuka  Madurai    Football  1200   20
2    Meena  Madurai      Hockey  1100   30
3   Suresh  Chennai     Cricket  1250   35
7    Leela    Salem  Throw ball  1500   42
8     Babu   Trichy  Throw ball  1400   22
9     Mani    Salem      Tennis  1300   28
10   Kumar  Chennai      Tennis  1300   25

In [ ]:
# Specific row and column value update

sport.loc[sport["Name"] == "Mani", "Sport"] = "Tenikoit"    # sport.loc[7, 'Sport'] = 45
sport.loc[sport["Name"] == "Kumar", "Sport"] = "Badminton"
sport

      Name Location       Sport  Fees  Age
1   Renuka  Madurai    Football  1200   20
2    Meena  Madurai      Hockey  1100   30
3   Suresh  Chennai     Cricket  1250   35
7    Leela    Salem  Throw ball  1500   42
8     Babu   Trichy  Throw ball  1400   22
9     Mani    Salem    Tenikoit  1300   28
10   Kumar  Chennai   Badminton  1300   25